server:
  port: 8080

database:
  HOST: "127.0.0.1"
  PORT: 5432
  DATABASE: lamhat
  USER_NAME: "lamhat_backend_dev"
  PASSWORD: "sdfghj"
  SSL_MODE: "disable"
  CLIENT_CERT: "/log"
  CLIENT_KEY: "/log"
  CA_CERT: "/log"

JWT_AUTH:
  SECRET_KEY: "PBb1LA6QHXe="
  TYPE: "jwt"
  JWT_EXP_IN_HRS: 24

OTP:
  OTP_LENGTH: 6
  OTP_VALIDITY_IN_MINS: 15

EMAIL:
  MAILGUN_DOMAIN: "YOUR-DOMAIN-HERE"
  MAILGUN_API: "YOUR-API-KEY"
  MAINGUN_SENDER: "SENDER-ID"

FILE_STORAGE:
  ENDPOINT: "your-minio-endpoint"
  ACCESS_KEY_ID: "your-access-key-id"
  ACCESS_SECRET: "your-secret"
  SSL: "true"
  LOCATION: "your-storage-location"
