server:
  port: 8080

database:
  HOST: "127.0.0.1"
  PORT: 5432
  DATABASE: lamhat
  USER_NAME: "lamhat_backend_dev"
  PASSWORD: "sdfghj"
  SSL_MODE: "disable"
  CLIENT_CERT: "/log"
  CLIENT_KEY: "/log"
  CA_CERT: "/log"

JWT_AUTH:
  SALT: "PBb1LA6QHXe="
  KEY: "PBb1LA6QHXe="

OTP:
  OTP_LENGTH: 6

EXAMPLE_VAR: "variable from config.yml"
EXAMPLE_PATH: "path from config.yml"
